version: '3'
services:
  sdk:
    build:
      context: .
      dockerfile: Dockerfile.ci
    depends_on: [proxy, node]
    entrypoint: docker/wait-for-it.sh node:3013 --
    env_file: [./docker/sdk.env]
    environment:
      - WALLET_PRIV=${WALLET_PRIV}
      - WALLET_PUB=${WALLET_PUB}
    volumes:
      - .:/app
      - .:/node_modules/@aeternity/aepp-sdk

  node:
    image: aeternity/epoch:${TAG}
    hostname: node
    expose: [3013, 3113, 3014, 3114]
    environment:
      EPOCH_CONFIG: /home/epoch/epoch.yaml
    command: -aecore expected_mine_rate ${EPOCH_MINE_RATE:-5000}
    volumes:
      - ${PWD}/docker/epoch_node_mean16.yaml:/home/epoch/epoch.yaml
      - ${PWD}/docker/keys/node:/home/epoch/node/keys
      - node_db:/home/epoch/node/data/mnesia
      - node_keys:/home/epoch/node/keys

  proxy:
    image: nginx:1.13.8
    hostname: proxy
    volumes:
      - ${PWD}/docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/docker/nginx-cors.conf:/etc/nginx/cors.conf
      - ${PWD}/docker/nginx-ws.conf:/etc/nginx/ws.conf

volumes:
  node_db:
  node_keys:
